#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

printf "Running yarn lint... \n"
if yarn lint &>/dev/null; then
  printf "${GREEN}Solidity code is valid${NC} \n"
else
  printf "${RED}Solidity code is invalid${NC} Please run yarn lint and fix problems \n"
  exit 1
fi

printf "Checking forge version... \n"
local_version=$(forge --version | cut -w -f 3 | cut -c 2-8)
remote_version=$(curl -s https://api.github.com/repos/foundry-rs/foundry/git/refs/tags | jq '.[] | select(.ref == "refs/tags/nightly") | .object.sha' | cut -c 2-8)
if [ "$local_version" == "$remote_version" ]; then
  printf "${GREEN}Forge version is up to date${NC} \n"
else
  printf "${RED}Forge version is outdated${NC} Please update forge to the latest version \n"
  printf "Local version: ${local_version} \n"
  printf "Remote version: ${remote_version} \n"
  exit 1
fi

printf "Running forge snapshot --diff... \n"
if FOUNDRY_PROFILE=default forge snapshot --check --no-match-test "testFuzz_*" &>/dev/null; then
  printf "${GREEN}No gas difference${NC} \n"
else
  printf "${RED}Gas difference${NC} Please run forge snapshot and add changes to the commit. \n"
  exit 1
fi
